apiVersion: skaffold/v4beta13
kind: Config
deploy:
    kubectl: {}
manifests:
    rawYaml:
        - ./infra/k8s/*.yaml
build:
    local:
        push: false
    artifacts:
        - image: herdeybayor/blog_client
          context: client
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.js"
                    dest: .
        - image: herdeybayor/blog_posts
          context: posts
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "*.js"
                    dest: .
        - image: herdeybayor/blog_comments
          context: comments
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "*.js"
                    dest: .
        - image: herdeybayor/blog_event-bus
          context: event-bus
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "*.js"
                    dest: .
        - image: herdeybayor/blog_query
          context: query
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "*.js"
                    dest: .
        - image: herdeybayor/blog_moderation
          context: moderation
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "*.js"
                    dest: .
